name: IonBeta
favicon: null
layout_spectrum: 0.20176125899888575
typography_spectrum: 0.7970414164010435
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4629070037044585
  lightness: 0.41236637393012643
  saturation: 0.8612388304900378
  rhythmicContrast: 0.2088425038382411
purpose: []
